filebeat.inputs:
  - type: log
    enabled: false
    paths:
       - /var/log/*.log
       - /var/log/auth.log
       - /var/log/syslog
  - type: container
    enabled: false
    paths:
      - "/var/lib/docker/containers/*/*.log"
filebeat.modules:
  - module: system
    syslog:
      enabled: true
    auth:
      enabled: true

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

setup.dashboards.enabled: true
setup.template.name: "filebeat"
setup.template.pattern: "filebeat-*"
setup.template.settings:
  index.number_of_shards: 1

processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~

output.elasticsearch:
  hosts: ["elk-0.node.consul:9200"]
  index: "filebeat-%{[agent.version]}-%{+yyyy.MM.dd}"

setup.kibana:
  host: "kibana.yair.live"
  protocol: "https"
  ssl.enabled: false
