---
- name: Restart dnsmasq service
  service:
    name: dnsmasq
    state: restarted


- name: Restart systemd-resolved service
  service:
    name: systemd-resolved.service
    state: restarted


- name: restart consul
  service:
    name: consul.service
    state: restarted
# handlers file for consul-server
