---
- name: start node_exporter service
  systemd:
    daemon_reload: yes
    name: node_exporter
    enabled: yes
    state: restarted

- name: restart consul service
  become: yes
  service:
    name: consul
    state: restarted