apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-deployment
  labels:
    app: {{ .Values.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        version: 3.0.0.998
        app: {{ .Values.name }}
    spec:
      serviceAccountName: opsschool-sa
      containers:
        - image: yairraiter/{{ .Values.name }}:{{ .Values.deployment.version }}
          name: {{ .Values.name }}-app
          ports:
            - containerPort: 5000
              name: http
              protocol: TCP
          env:
            - name: FLASK_ENV
              value: development
            - name: AWS_DEFAULT_REGION
              value: us-east-1
            - name: AWS_ACCESS_KEY_ID
              value: mock_key
            - name: AWS_SECRET_ACCESS_KEY
              value: mock_key