apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-service
spec:
  selector:
    app: {{ .Values.name }}
  type: ClusterIP
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 5000
