---
- name: Remove apt lock file
  file:
    state: absent
    path: "/var/lib/dpkg/lock"

- name: install dnsmasq
  apt:
    name:
      - dnsmasq
    state: present
    update_cache: yes

- name: Enable and restart dnsmasq service
  service:
    name: dnsmasq
    enabled: yes


- name: configure dnsmasq
  copy:
    src: ./files/dnsmasq.conf
    dest: "{{ dnsmasq_configuration_file }}"
    mode: 0644
  notify:
    - Restart dnsmasq service
